name: Kildomaten

on:
  workflow_call:

permissions:
  contents: "read"
  id-token: "write"
  issues: "write"
  pull-requests: "write"
  statuses: "read"

jobs:
  workflow_gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch main
        run: |
          if [ "$(git branch --show-current)" != "main" ]; then
            echo "Current branch is not main"
            git fetch origin main:main
          fi

      - name: Check that diff is in automation/**
        id: check_diff_variables
        run: |
          # Check for changes in the specific directory compared to the main branch
          CHANGED_FILES=$(git diff --name-only main -- automation/source_data/)

          # Check if the variable CHANGED_FILES is not empty
          if [ "$(git branch --show-current)" == "main" ]; then
            echo "Running on main branch"
            echo "should_run_fetch_sources=true" >> $GITHUB_OUTPUT
          elif [ -z "$CHANGED_FILES" ]; then
            echo "Error: No changes detected in automation/source_data/ compared to main branch."
            echo "should_run_fetch_sources=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in automation/source_data/"
            echo "should_run_fetch_sources=true" >> $GITHUB_OUTPUT
          fi
    outputs:
      should_run_fetch_sources: ${{steps.check_diff_variables.outputs.should_run_fetch_sources}}

  fetch_sources:
    if: ${{ needs.workflow_gatekeeper.outputs.should_run_fetch_sources == 'true' }}
    needs: [workflow_gatekeeper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Confirm Activation of 'source-data-automation'
        run: |
          result=$(yq e -o=json infra/projects.yaml | jq '.projects[] | select(.features | index("source-data-automation"))')

          if [ -z "$result" ]; then
              echo "Error: The 'source-data-automation' feature is disabled for all projects."
              exit 1
          fi
      - name: Set output variables
        id: step_output_variables
        run: |
          team=$(yq '.team_uniform_name' "$GITHUB_WORKSPACE/infra/projects.yaml")
          echo "team_name=$team" >> $GITHUB_OUTPUT
          
          gar_project_id="artifact-registry-5n"
          service_account="gh-actions-${team}@${gar_project_id}iam.gserviceaccount.com"
          echo "service_account=$service_account" >> $GITHUB_OUTPUT
          
          base_registry="europe-north1-docker.pkg.dev/${gar_project_id}/dapla-felles-docker/automation/source_data"
          echo "base_registry=$base_registry" >> $GITHUB_OUTPUT
          
          team_registry="europe-north1-docker.pkg.dev/${gar_project_id}/${team}-docker/automation/source_data"
          echo "team_registry=$team_registry" >> $GITHUB_OUTPUT
          
          gar_project_number=${{secrets.GAR_PROJECT_NUMBER }}
          workload_identity_provider="projects/${gar_project_number}/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
          echo "workload_identity_provider=$workload_identity_provider" >> $GITHUB_OUTPUT


      - name: Create matrix
        id: step_create_matrix
        run: |
          MATRIX="["
          first=true
          
          for folder in automation/source_data/*/*; do
            if [ -d "$folder" ]; then
              [ "$first" = false ] && MATRIX+=','
              env=$(basename "$(dirname "$folder")")
              source=$(basename "$folder")
              MATRIX+="\"$source,$env\""
              first=false
            fi
          done
          MATRIX+="]"
          
          # Check if the matrix is empty
          if [ "$MATRIX" = "[]" ]; then
            echo "Error: Could not find any sources for Kildomaten. Please verify that your source configuration matches the description in the Dapla manual: https://manual.dapla.ssb.no/automatisering.html#konfigurere-en-kilde"
            exit 1
          fi
          
          echo "Matrix value: $MATRIX"
          echo "env_matrix=$MATRIX" >> $GITHUB_OUTPUT
    outputs:
      team_name: ${{steps.step_output_variables.outputs.team_name}}
      service_account: ${{steps.step_output_variables.outputs.service_account}}
      base_registry: ${{steps.step_output_variables.outputs.base_registry}}
      team_registry: ${{steps.step_output_variables.outputs.team_registry}}
      workload_identity_provider: ${{steps.step_output_variables.outputs.workload_identity_provider}}
      matrix: ${{ steps.step_create_matrix.outputs.env_matrix }}

  test:
    if: ${{ needs.workflow_gatekeeper.outputs.should_run_fetch_sources == 'true' && github.event_name != 'push' }}
    needs: [fetch_sources]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(needs.fetch_sources.outputs.matrix)}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          workload_identity_provider: ${{ needs.fetch_sources.outputs.workload_identity_provider }}
          service_account: ${{ needs.fetch_sources.outputs.service_account }}
          token_format: "access_token"
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ needs.fetch_sources.outputs.base_registry }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Pull base image
        run: docker pull ${{ needs.fetch_sources.outputs.base_registry }}/base-image:main
      - name: Clone test scripts
        run: |
          git clone -b v2.1.0 https://github.com/statisticsnorway/dapla-source-data-processor-build-scripts
      - name: Run tests for ${{ matrix.source }}
        run: |
          MATRIX=${{ matrix.source }}
          IFS=',' read -r FOLDER_NAME ENV_NAME <<< "$MATRIX"
          echo "Running test for source: $FOLDER_NAME-$ENV_NAME"
          docker run -v "$(pwd):/workspace" \
          -w /workspace \
          -e ENV_NAME="$ENV_NAME" \
          -e FOLDER_NAME="$FOLDER_NAME" \
          ${{ needs.fetch_sources.outputs.base_registry }}/base-image:main \
          dapla-source-data-processor-build-scripts/analyze_source_files.sh

  plan:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [test]
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Ready comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: context.issue.number,
              body: 'Auto-apply is ready, approve PR to start'
            })

  checks:
    if: ${{ github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved' }}
    needs: [test]
    name: Check preconditions
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is mergeable
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            if (!pr.mergeable) {
              core.setFailed("PR needs to be approved and mergeable");
            }

  atlantis_auto_apply:
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Wait for plan
        uses: statisticsnorway/dapla-source-data-processor-build-scripts/.github/actions/wait-for-status@main
        with:
          timeout: 300
          sleep_time: 5
          initial_sleep: 10
          statuses: |
            atlantis/plan

      - name: Apply
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: context.issue.number,
              body: 'atlantis apply'
            })

      - name: Wait for apply
        uses: statisticsnorway/dapla-source-data-processor-build-scripts/.github/actions/wait-for-status@main
        with:
          timeout: 300
          sleep_time: 5
          initial_sleep: 10
          fail_on_destroy: false
          statuses: |
            atlantis/apply

  build_and_push:
    if: ${{ github.event_name == 'push' }}
    needs: [ fetch_sources ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ${{fromJson(needs.fetch_sources.outputs.matrix)}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          workload_identity_provider: ${{ needs.fetch_sources.outputs.workload_identity_provider }}
          service_account: ${{ needs.fetch_sources.outputs.service_account }}
          token_format: "access_token"
      - name: Login to base registry
        uses: docker/login-action@v2
        with:
          registry: ${{ needs.fetch_sources.outputs.base_registry }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Pull base image
        run: docker pull ${{ needs.fetch_sources.outputs.base_registry }}/base-image:main
      - name: Login to team registry
        uses: docker/login-action@v2
        with:
          registry: ${{ needs.fetch_sources.outputs.team_registry }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Build and push image for ${{ matrix.source }}
        run: |
          MATRIX=${{ matrix.source }}
          IFS=',' read -r SOURCE_NAME PROJECT_NAME <<< "$MATRIX"
          echo "Building image for source: $SOURCE_NAME-$PROJECT_NAME"
          echo $'FROM ${{ needs.fetch_sources.outputs.base_registry }}/base-image:main\nCOPY automation/source_data/$PROJECT_NAME/$SOURCE_NAME/. ./plugins' > Dockerfile
          docker build . -t ${{ needs.fetch_sources.outputs.team_registry }}/$SOURCE_NAME:$PROJECT_NAME
          docker push ${{ needs.fetch_sources.outputs.team_registry }}/$SOURCE_NAME:$PROJECT_NAME

  deploy_sources:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build_and_push
    strategy:
      matrix:
        source: ${{fromJson(needs.fetch_sources.outputs.matrix)}}
    steps:
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          workload_identity_provider: ${{ needs.fetch_sources.outputs.workload_identity_provider }}
          service_account: ${{ needs.fetch_sources.outputs.service_account }}
          token_format: "access_token"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      - name: 'Output project display name and source name'
        id: source_metadata
        run: |
          MATRIX=${{ matrix.source }}
          IFS=',' read -r SOURCE_NAME PROJECT_DISPLAY_NAME <<< "$MATRIX"
          echo project_display_name=$PROJECT_DISPLAY_NAME >> $GITHUB_OUTPUT
          echo source_name=$SOURCE_NAME >> $GITHUB_OUTPUT
      - name: 'Output project name'
        id: get_project_name
        env:
          PROJECT_DISPLAY_NAME: ${{ steps.source_metadata.outputs.project_display_name }}
        run: |
          import os
          project_display_name = os.getenv("PROJECT_DISPLAY_NAME")
          environment = project_display_name.split("-")[-1]
          length_of_environment = len(environment)
          project_name = project_display_name[:1-length_of_environment]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f'project_name={project_name}', file=fh)
        shell: python
      - name: Output project id
        id: get_project_id
        run: |
          project_name=${{steps.get_project_name.outputs.project_name}}
          project_id=$(gcloud projects list --filter="name:${project_name}" | awk 'NR==2 {print $1}')
          echo project_id=$project_id >> $GITHUB_OUTPUT
      - name: Output SA email
        id: output_sa_email
        env:
          PROJECT_ID: ${{ steps.get_project_id.outputs.project_id }}
          SOURCE_NAME: ${{ steps.source_metadata.outputs.source_name }}
        run: |
          SA_EMAIL="gha-${SOURCE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
          echo $SA_EMAIL
          echo sa_email=$SA_EMAIL >> $GITHUB_OUTPUT
      - id: "auth-project-sa"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.1.1"
        with:
          workload_identity_provider: ${{ needs.fetch_sources.outputs.workload_identity_provider }}
          service_account: ${{steps.output_sa_email.outputs.sa_email}}
          token_format: "access_token"
      - name: 'Set up Cloud SDK with project SA'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: 'Deploy source: ${{ matrix.source }}'
        env:
          PROJECT_ID: ${{ steps.get_project_id.outputs.project_id }}
          SOURCE_NAME: ${{ steps.source_metadata.outputs.source_name }}
          ENV_NAME: ${{ steps.source_metadata.outputs.project_display_name }}
          DISPLAY_TEAM_NAME: ${{ needs.fetch_sources.outputs.team_name }}
          TEAM_REGISTRY: ${{ needs.fetch_sources.outputs.team_registry}}
        run: |
          echo "Updating image used by cloud run for: ${SOURCE_NAME} in environment: ${ENV_NAME}"
          PROCESSOR_NAME="source-${DISPLAY_TEAM_NAME}-processor"
          gcloud run deploy $PROCESSOR_NAME --image $TEAM_REGISTRY/$SOURCE_NAME:$ENV_NAME --region europe-north1 --project $PROJECT_ID
